import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NavbarWrapper from "@/components/NavbarWrapper";

export const metadata: Metadata = {
  title: "Controle de Chaves",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-Br">
      <body>
        <header>
          <NavbarWrapper className="bg-[#003B2F] text-white" />
        </header>
        {children}
      </body>
    </html>
  );
}
