import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Controle de Chaves",
  description: "Generated by create next app",
};

const pages = [
  {
    name: "Chaves institucionais", path: "", options:
      [
        { name: "Consulta de chaves", path: "/consultas/chaves" },
        { name: "Consulta de entregas", path: "/consultas/entregas" },
        { name: "Entregas em aberto", path: "/consultas/entregas/abertas" },
        { name: "Cadastro de chaves", path: "/cadastros/chaves" },
        { name: "Cadastro de permissão", path: "/cadastros/permissao" },
        { name: "Cadastro de armários de chaves", path: "/cadastros/chavesArmarios" },
      ]
  },
  {
    name: "Armários dos Vestiários", path: "", options:
      [
        { name: "Armários Disponíveis", path: "/armarios/disponiveis" },
        { name: "Armários Ocupados", path: "/armarios/ocupados" },
        { name: "Segunda via", path: "/armarios/segundaVia" },
        { name: "Histórico", path: "/armarios/historico" },
      ]
  }
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="pt-Br">
      <body>
        <header>
          <Navbar className="bg-[#003B2F] text-white" pages={pages} />
          </header>
          {children}
      </body>
    </html>
  );
}
